name: lerobot_rdt
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.11.4=h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=25.3=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.0=h12debd9_5
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py310h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - accelerate==1.12.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - async-timeout==5.0.1
      - attrs==25.4.0
      - av==15.1.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cloudpickle==3.1.2
      - cmake==4.1.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.1.1
      - deepdiff==8.6.1
      - deepspeed==0.14.2
      - diffusers==0.35.2
      - dill==0.4.0
      - dnspython==2.8.0
      - docker-pycreds==0.4.0
      - draccus==0.10.0
      - einops==0.8.1
      - evdev==1.9.2
      - farama-notifications==0.0.4
      - filelock==3.13.1
      - flash-attn==2.8.3
      - fonttools==4.60.1
      - frozenlist==1.8.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gymnasium==1.2.2
      - h5py==3.11.0
      - hf-transfer==0.1.9
      - hf-xet==1.2.0
      - hjson==3.1.0
      - huggingface-hub==0.35.3
      - idna==3.11
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - imgaug==0.4.0
      - importlib-metadata==8.7.0
      - inquirerpy==0.3.4
      - jinja2==3.1.4
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lerobot==0.4.2
      - markupsafe==2.1.5
      - matplotlib==3.10.7
      - mergedeep==1.3.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.16
      - mypy-extensions==1.1.0
      - networkx==3.3
      - ninja==1.13.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-ml-py==13.580.82
      - nvidia-ml-py3==7.352.0
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.6.77
      - nvitop==1.5.3
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.12.0.88
      - orderly-set==5.5.0
      - packaging==25.0
      - pandas==2.3.3
      - peft==0.10.0
      - pfzy==0.3.4
      - pillow==11.0.0
      - platformdirs==4.5.0
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - protobuf==4.25.8
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pydantic==2.12.0
      - pydantic-core==2.41.1
      - pymongo==4.15.4
      - pynput==1.8.1
      - pynvml==13.0.1
      - pyparsing==3.2.5
      - pyserial==3.5
      - python-dateutil==2.9.0.post0
      - python-xlib==0.33
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyyaml-include==1.4.1
      - regex==2025.9.18
      - requests==2.32.5
      - rerun-sdk==0.26.2
      - safetensors==0.6.2
      - scikit-image==0.25.2
      - scipy==1.15.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.41.0
      - setproctitle==1.3.7
      - shapely==2.1.2
      - six==1.17.0
      - smmap==5.0.2
      - sympy==1.13.3
      - termcolor==3.2.0
      - tifffile==2025.5.10
      - timm==1.0.3
      - tokenizers==0.15.2
      - toml==0.10.2
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchcodec==0.5
      - torchvision==0.22.1
      - tqdm==4.67.1
      - transformers==4.38.2
      - triton==3.3.1
      - typing-extensions==4.15.0
      - typing-inspect==0.9.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wandb==0.21.4
      - wcwidth==0.2.14
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
prefix: /share_data/chensiqi/miniconda3/envs/lerobot_rdt
